import { describe, expect, it } from 'vitest'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { formatFabBench, runFabBenchmark } from './fabFixtures'

describe('Stage 9 fabrication fixtures', () => {
  it('runs fabrication fixtures A–J; evo never worse than BLF', () => {
    const rows = runFabBenchmark()
    expect(rows.length).toBe(20) // 10 × blf+evo
    // eslint-disable-next-line no-console
    console.log('\n' + formatFabBench(rows) + '\n')

    const byId = new Map<string, { blf?: (typeof rows)[0]; evo?: (typeof rows)[0] }>()
    for (const r of rows) {
      const e = byId.get(r.id) ?? {}
      if (r.engine === 'blf') e.blf = r
      else e.evo = r
      byId.set(r.id, e)
    }
    for (const [, pair] of byId) {
      if (!pair.blf || !pair.evo) continue
      expect(pair.evo.unplaced).toBeLessThanOrEqual(pair.blf.unplaced)
      expect(pair.evo.score).toBeLessThanOrEqual(pair.blf.score + 1e-3)
    }

    const md = [
      '# Stage 9 — After optimization',
      '',
      'Generated by `fabFixtures` test (fast preset, 500ms, seed=9).',
      '',
      '```',
      formatFabBench(rows),
      '```',
      '',
    ].join('\n')
    writeFileSync(
      resolve(__dirname, '../../docs/benchmarks/stage-9-after.md'),
      md,
    )

    // Compact before/after style table vs BLF (same run)
    const cmp: string[] = [
      '# Stage 9 — BLF vs evolutionary (same fixtures)',
      '',
      '| Fixture | BLF sheets | Evo sheets | BLF util% | Evo util% | BLF waste | Evo waste | Δ waste% | Δ util pp | BLF ms | Evo ms | runtime× |',
      '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    ]
    for (const [id, pair] of byId) {
      if (!pair.blf || !pair.evo) continue
      const bw = pair.blf.waste
      const ew = pair.evo.waste
      const dWaste = bw > 0 ? ((bw - ew) / bw) * 100 : 0
      const dUtil = (pair.evo.utilization - pair.blf.utilization) * 100
      const rt =
        pair.blf.ms > 0 ? pair.evo.ms / pair.blf.ms : Number.POSITIVE_INFINITY
      cmp.push(
        `| ${id} | ${pair.blf.sheets} | ${pair.evo.sheets} | ${(pair.blf.utilization * 100).toFixed(1)} | ${(pair.evo.utilization * 100).toFixed(1)} | ${bw.toFixed(0)} | ${ew.toFixed(0)} | ${dWaste.toFixed(1)} | ${dUtil.toFixed(2)} | ${pair.blf.ms.toFixed(0)} | ${pair.evo.ms.toFixed(0)} | ${rt.toFixed(1)} |`,
      )
    }
    cmp.push('')
    writeFileSync(
      resolve(__dirname, '../../docs/benchmarks/stage-9-comparison.md'),
      cmp.join('\n'),
    )
  }, 300_000)
})
