import { describe, expect, it } from 'vitest'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { formatFabBench, runFabBenchmark } from './fabFixtures'

describe('Stage 9 fabrication fixtures', () => {
  it('runs fabrication fixtures A–J; automatic never regresses from its exact seed', () => {
    const rows = runFabBenchmark()
    expect(rows.length).toBe(20) // 10 × BLF + automatic
    expect(new Set(rows.map(({ engine }) => engine))).toEqual(
      new Set(['blf', 'automatic']),
    )
    // eslint-disable-next-line no-console
    console.log('\n' + formatFabBench(rows) + '\n')

    const byId = new Map<string, { blf?: (typeof rows)[0]; automatic?: (typeof rows)[0] }>()
    for (const r of rows) {
      const e = byId.get(r.id) ?? {}
      if (r.engine === 'blf') e.blf = r
      else e.automatic = r
      byId.set(r.id, e)
    }
    for (const [, pair] of byId) {
      if (!pair.blf || !pair.automatic) continue
      expect(pair.automatic.canonicalVsSeed).not.toBeNull()
      expect(pair.automatic.canonicalVsSeed).toBeLessThanOrEqual(0)
    }

    const md = [
      '# Stage 9 — After optimization',
      '',
      'Generated by `fabFixtures` test (automatic search, seed=9).',
      '',
      '```',
      formatFabBench(rows),
      '```',
      '',
    ].join('\n')
    if (process.env.UPDATE_BENCHMARK_DOCS === '1') {
      writeFileSync(
        resolve(__dirname, '../../docs/benchmarks/stage-9-after.md'),
        md,
      )
    }

    // Compact before/after style table vs BLF (same run)
    const cmp: string[] = [
      '# Stage 9 — BLF vs automatic (same fixtures)',
      '',
      '| Fixture | BLF sheets | Automatic sheets | BLF util% | Automatic util% | BLF waste | Automatic waste | Δ waste% | Δ util pp | BLF ms | Automatic ms | runtime× |',
      '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    ]
    for (const [id, pair] of byId) {
      if (!pair.blf || !pair.automatic) continue
      const bw = pair.blf.waste
      const ew = pair.automatic.waste
      const dWaste = bw > 0 ? ((bw - ew) / bw) * 100 : 0
      const dUtil = (pair.automatic.utilization - pair.blf.utilization) * 100
      const rt =
        pair.blf.finalMs > 0
          ? pair.automatic.finalMs / pair.blf.finalMs
          : Number.POSITIVE_INFINITY
      cmp.push(
        `| ${id} | ${pair.blf.sheets} | ${pair.automatic.sheets} | ${(pair.blf.utilization * 100).toFixed(1)} | ${(pair.automatic.utilization * 100).toFixed(1)} | ${bw.toFixed(0)} | ${ew.toFixed(0)} | ${dWaste.toFixed(1)} | ${dUtil.toFixed(2)} | ${pair.blf.finalMs.toFixed(0)} | ${pair.automatic.finalMs.toFixed(0)} | ${rt.toFixed(1)} |`,
      )
    }
    cmp.push('')
    if (process.env.UPDATE_BENCHMARK_DOCS === '1') {
      writeFileSync(
        resolve(__dirname, '../../docs/benchmarks/stage-9-comparison.md'),
        cmp.join('\n'),
      )
    }
  }, 300_000)
})
